
"""
Use this Fibonacci cypher to encode a given message.
The Fibonacci sequence starts with two non-negative integers and every term after that is the
sum of the two previous numbers. Therefore, for this problem, our Fibonacci sequence will be 1,
2, 3, 5, 8, 13, ... so that all terms are unique numbers. A Fibonacci cypher uses these numbers
and an inputted ‘key’ (a lower-case letter in the alphabet) to encode a message into a series of
numbers. Another person can decipher the message by knowing the ‘key’ that was used. For
each character in the message, integers are generated by using the following steps:
1. Find the Fibonacci number with the same index as the character (e.g. the 1st character in
the inputted string uses the Fibonacci number 1 and the 5th character uses the number 8).
2. By using the inputted key, find a new letter that is offset by the Fibonacci number found
in Step 1. Wrap around to the beginning of the alphabet if necessary (e.g. if the key = ‘p’
and the Fibonacci number is 21, then the new letter is ‘k’).
3. Find the encoded number for each letter in the message by adding the ASCII code of the
character in the string and the ASCII code of the letter found in Step 2.

EXAMPLE: For the string “ACSL c2” and the letter ‘h’ (this is the key) the numbers are found as shown:
Fibonacci offset Offset ASCII Code String ASCII code Calculation
h + 1 = i i = 105 A = 65 65 + 105 = 170
h + 2 = j j = 106 C = 67 67 + 106 = 173
h + 3 = k k = 107 S = 83 83 + 107 = 190
h + 5 = m m = 109 L = 76 76 + 109 = 185
h + 8 = p p = 112 space = 32 32 + 112 = 144
h + 13 = u u = 117 c = 99 99 + 117 = 216
h + 21 = c c = 99 2 = 50 50 + 99 = 149
The encoded message is “170 173 190 185 144 216 149”.
INPUT: There are 5 sets of data. Each set contains 2 data values: 1) a lower-case alphabetic
character for the ‘key’ and 2) a string for the actual message to be encoded. We guarantee that
the message will be no longer than 30 characters. Any typeable character on the keyboard
except for double quotes may be included in the message.
OUTPUT: For each line of data, print the integers, each separated by a single space, that
represent the encoded message.
"""


class Solution:
    def encode(self, msg, key):
        # make fibbonachi key(30)
        fibskey = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269]
        # ASCII ord('C') converts the letter to ASCII
        key = ord(key)
        # Add the fib key with the "The key" mod result by 26 Wrap it around the alphabet
        result = []
        for i in range(len(msg)):
            position = key - ord('a')
            new_position = (position + fibskey[i])%26
            result.append(new_position + ord('a'))
            
        #print(key)
        # Add result with message letter by letter no mod
        final_result = []
        for i in range(len(msg)):
            a = ord(msg[i]) + result[i]
            final_result.append(str(a))
        #print(final_result)
        # return the result of all the numbers in a string with spaces
        string = " ".join(final_result)
        return string

    def decode(self, code, key):
        pass

if __name__ == '__main__':
    import sys

    sys.setrecursionlimit(1501)
    sol = Solution()
    tests = [("ACSL c2", "h"), ("Python Programming", "s"), ("Fibonacci Numbers", "a"), ("Help ME!", "j"), ("It is 9:30 in the morning.","z")]
    outputs = [("170 173 190 185 144 216 149"), ("196 238 234 224 208 212 142 177 232 211 206 228 199 210 223 205 209 213"), ("168 204 198 213 215 207 217 204 205 140 189 239 219 207 223 222 222"),
               ("179 209 217 223 146 196 170 147"), ("170 214 131 206 219 141 174 162 150 155 142 226 219 140 237 211 207 149 210 233 215 211 211 221 224 156")]
    for i in range(len(tests)):
        msg, key = tests[i]
        answer = sol.encode(msg, key)
        if answer == outputs[i]:
            print("👍👏Yippeee")
            print(answer)
            print(outputs[i])
        elif answer != outputs[i]:
            print("BOOOOOOOOOOOOO >:( 🤮😱🤮😱🤮😱🤮😱🤮😱🤮😱")
            print(answer)
            print(outputs[i])